# task_name, included in the image name
task: SKYMAPPER0029-CAM1

# image paths or image directory path
path: E:/CLASP/20221027
postfix: fits

# number of loaded images: num(int), [start, end](list), 'all'(str)
num_imgs: all
# parameters of image preprocessing
params_pre:
  # scale the image to x% of the original size
  scale: 0.2

# parameters of source extraction
params_ext:
  # extraction algorithm, support 'sep' and 'nth' now
  method: sep
  # the threshold of image segmentation
  threshold: 3
  # ratio of deblending
  deblend: 1.0
  # kernel size of NTH algorithm
  kernel_size: [5, 9]
  # ignored regions of image boundary
  boundary: 3

# parameters of image registration, only support triangle registration now
params_reg:
  # the number of extracted stars 
  num_stars: 36
  # the length threshold for triangle matching
  ratio_len: 0.05
  # the length threshold for incorrect triangle transormation
  th_length: 100

# parameters of non-target filtering
params_nontar:
  # the distance threshold for non-target filtering
  distance_threshold: 10

# parameters of track association
params_track:
  # search radius for initial track search  50
  search_radius: 50
  # search radius for track association     15
  association_radius: 15
  # ignored regions of image boundary
  r_boundary: 10
  # vectorial angle threshold of two tracks
  angle_threshold: 25
  # track length threshold for true track filtering
  length_threshold: 10
  # track confidence threshold for true track filtering
  confidence_threshold: 0.7

# parameters for display & save
params_display:
  # whether to display the image
  display: false
  # whether to save the detected results in each image
  save: true
  # whether to export the detected results to a csv file
  export: true
  # whether to print the detected results
  print: true
